# Document:
# http://simiki.org/docs/configuration.html

url: 
title: Knowledge Change Destiny
keywords: Mechine Learning , Economics , Mathematics 
description: More Reading , More Possibilities
author: Cimon

root: /wiki

deploy:
    - type: git
      remote: origin
      branch: gh-pages
      
theme: simple